# Generated by Django 4.2.9 on 2024-02-03 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Minibus', 'Minibus'), ('Crossover', 'Crossover'), ('Sports Car', 'Sports Car'), ('Other', 'Other'), ('Pickup', 'Pickup')])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980, 'Year must be between 1980 and 2049!'), django.core.validators.MaxValueValidator(2049, 'Year must be between 1980 and 2049!')])),
                ('image_url', models.URLField(error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, help_text='https://...', unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_owner.profile')),
            ],
        ),
    ]
