# Generated by Django 4.2.9 on 2024-02-10 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0, 'Price must be at least 1.0!'), django.core.validators.MaxValueValidator(135000000.0, 'Price must be at most 135000000.0!')]),
        ),
    ]
