# Generated by Django 4.2.4 on 2024-02-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_owner', '0003_alter_profile_age_alter_profile_email_and_more'),
        ('car', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_owner.profile'),
        ),
    ]
