# Generated by Django 4.2.9 on 2024-02-08 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(help_text='Age requirement: 18 years and above.', validators=[django.core.validators.MinValueValidator(18, 'Age requirement: 18 years and above.')]),
        ),
    ]
